[package]
name = "day_07"
version = "0.1.0"
authors = ["Valentin Tolmer <valentin.tolmer@gmail.com>"]
edition = "2018"

[dependencies]
nom = "*"
derive_more = "*"
itertools = "*"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "day_07"
path = "src/main.rs"
