[package]
name = "day_01"
version = "0.1.0"
authors = ["Valentin Tolmer <valentin.tolmer@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "day_01"
path = "src/main.rs"
